### PR TITLE
Fixed: Routes.json validation rules for columns and cards moves.

### PR DESCRIPTION
**Pull request by slavahatnuke**
- fixed routes.json validation for project cards and columns
- "move-project-card" description typo

```
github.projects.moveProjectCard({ position: 'after:3456', id: 1234, column_id: 100200  });
```

Did not work. It was issue with RegEx 
- `\\d` -> `\\d+`
- `^(top|bottom|after:\\d)$` -> `^(top|bottom|after:\\d+)$`.

### CODE REVIEW

**Comment by slavahatnuke** [comment]
@kaizensoze @gr2m Hi. Could you take a look and if possible merge? It's simple validation rule updates and it would be great to have this working in package. Thx, Slava

**Comment by gr2m** [comment]
I can look into it on Wednesday, I’m out until then

**Comment by slavahatnuke** [comment]
Hi @gr2m thank you, it would be great to have it on board, because developing project with your package. Really thank you for the solution!

**Comment by slavahatnuke** [comment]
@kaizensoze @gr2m Hi guys, is it possible to take a look on this small validation rules update?
It would help me to solve issues in my project. Thank you.

**Comment by slavahatnuke** [comment]
Hi @gr2m . Please could you take a look on this?

**Comment by gr2m** [comment]
I’m looking into it. I want to add tests to reproduce the problem first.

**Comment by slavahatnuke** [comment]
@gr2m thanks a lot!

Really the issue here that `id` IS NOT `\d{1}`. Real card id IS `\d+`.
Thx.

**Pull request closed without merging**
