### PR TITLE
Fix README case format for clientId, clientSecret

### PR DESCRIPTION
**Pull request by cooperka**
Code usage in [authentication/validate.js](https://github.com/octokit/rest.js/blob/master@%7B2019-01-27%7D/plugins/authentication/validate.js#L16) and [authentication/before-request.js](https://github.com/octokit/rest.js/blob/master@%7B2019-01-27%7D/plugins/authentication/before-request.js#L25).

[View rendered README.md](https://github.com/cooperka/rest.js/blob/patch-1/README.md)

### CODE REVIEW

**Comment by gr2m** [comment]
Oh my, good catch! Thanks for the pull request! Yes, Typescript definitions only need to updated at 
https://github.com/octokit/rest.js/blob/0e116993109603cfaa6b2d00feacf27a1e2dec5b/scripts/templates/index.d.ts.tpl#L45-L47

**Comment by cooperka** [comment]
@gr2m done :hibiscus:

**Review by wolfy1339 — APPROVED** [review]
Thanks 👍

**Review by gr2m — APPROVED** [review]
Thanks 💐

**Comment by gr2m** [comment]
Thanks for the review @wolfy1339 👍

**Pull request merged**
