### PR TITLE
fix: artifacts response definition

### PR DESCRIPTION
**Pull request by bokuweb**
fix ` ActionsListWorkflowRunArtifactsResponse`.
I'm trying `octokit.actions.listWorkflowRunArtifacts` however response type mismatch.

### current definition

```
[
  {
    "total_count": 2,
    "artifacts": [...],
  }
]
```

### current real response

```
{
  "total_count": 2,
  "artifacts": [...],
}
```

### CODE REVIEW

**Comment by gr2m** [comment]
The types are generated from the docs, the response is incorrect there: https://developer.github.com/v3/actions/artifacts/#list-workflow-run-artifacts

Once that's fixed, this is going to resolve itself. I'll let the docs team now about it, thank you :)

**Comment by gr2m** [comment]
They are already aware of the problem and are working on it

**Comment by bokuweb** [comment]
@gr2m 
> The types are generated from the docs 

Oops I missed it ... Thanks :)

**Comment by gr2m** [comment]
Absolutely not your fault, I'll make the architecture more clear with the upcoming version :)

You issue should be resolved via https://github.com/octokit/rest.js/pull/1578

**Pull request closed without merging**
