### PR TITLE
fixes #711

### LINKED ISSUE #711: typings: getForRepo returns Promise<Github.AnyResponse> instead of a promise for an iterable
I used to be able to do

```
for (const issue of await octokit.issues.getForRepo({ owner, repo, state: 'open', labels: 'translation' })) {
...
}
```

but now I get

```
error TS2488: Type must have a '[Symbol.iterator]()' method that returns an iterator.
```

### PR DESCRIPTION
**Pull request by retorquere**
The typings were missing an iterator for methods that return arrays

fixes #711

### CODE REVIEW

**Comment by gr2m** [comment]
looks like there is a syntax error now? https://travis-ci.org/octokit/rest.js/jobs/331701372#L2074

You can reproduce it locally by running `npm run validate:ts`

**Comment by gr2m** [comment]
@orta could you please have a quick glance if this looks good?
https://github.com/octokit/rest.js/pull/713/files

**Comment by orta** [comment]
@gr2m feel free to ping me any time 👍

**Comment by orta** [comment]
@retorquere this PR makes sense in terms of the code in https://github.com/octokit/rest.js/issues/711, but TBH, I'm a bit surprised the old version worked - shouldn't you have to take the response out of `data` ?

**Comment by retorquere** [comment]
I don't know, I've been delivering releases this way with 13.1 for a long while now, so it seemed to work  ¯\\\_(ツ)_/¯

**Comment by orta** [comment]
Heh, well the d.ts is meant to describe the data - and if it works, it works

This is 👍 from me

**Review by gr2m — APPROVED** [review]

**Pull request merged**
