### PR TITLE
Clarify what errors to expect and how the library really works.

### PR DESCRIPTION
**Pull request by webbertakken**
After finally having figured out that there are several authentication scopes and one does not include the other, after ready [this](https://github.com/octokit/octokit.net/blob/main/docs/github-apps.md#authentication) and all related docs several times I managed to implement a method that uses the `installation` scope for a GitHub App.

Some things definitely threw me off at first and I have tried to write the yeast of it as concise as possible.

Hope this will help future implementers.

-----
[View rendered docs/src/pages/api/01_authentication.md](https://github.com/webbertakken/rest.js/blob/patch-1/docs/src/pages/api/01_authentication.md)

### CODE REVIEW

**Review by oscard0m — APPROVED** [review]

**Review by wolfy1339 — APPROVED** [review]

**Comment by oscard0m** [comment]
What's missing to move this PR forward? To update the branch, right?

**Review by gr2m — COMMENTED** [review]
oh my I made a review but didn't submit 🤦🏼

**Comment by gr2m** [comment]
@wolfy1339 if you don't mind I'd prefer to revert the changes

**Comment by wolfy1339** [comment]
Go ahead

**Comment by webbertakken** [comment]
Would you rephrase it in a better way, as you have a lot more in depth knowledge about it than I. 

The goal was especially to help implementers understand these nuances better.

**Comment by gr2m** [comment]
I took a stab at it here: https://github.com/octokit/rest.js/pull/1897

**Pull request merged**
