### PR TITLE
WIP User Migrations

### PR DESCRIPTION
**Pull request by sgvictorino**
I am making a first attempt at building user migrations into this library. If anyone would be willing to review the code and spot bugs or typos so this feature can possibly be merged in the future, that would be great.
Thanks in advance!

### CODE REVIEW

**Comment by gr2m** [comment]
Hey @bitsol thanks for starting that. The routes.json files are updated automatically now using https://github.com/octokit/routes, but new routes need to be added manually still. Let me have a look into it

**Comment by sgvictorino** [comment]
@gr2m I wish I had seen octokit/routes before. Is this PR still useful? With https://github.com/octokit/routes/commit/7f5a3f15e4e7c717a2b5f5d81fca3d9247a27c48, shouldn't routes.json have the user migration routes already? I thought I was simply adding a feature and clarifying route names, but that was already done?

**Comment by gr2m** [comment]
@bitsol the PR is great, thanks! I totally missed the fact that we are lacking the User Migration APIs. Based on that I found some problems with the API Docs on migrations for both User & Organization Migrations, to help better distinguish the method names that will be are derived from the section titles in the v3 REST API docs. So your input was super valuable 👍 I can take it from here

If this is an urgent blocker for you right now? Or can it wait another few days?

**Comment by sgvictorino** [comment]
Thank you so much!
The PR doesn't have to be reviewed and merged today or even tomorrow, as I could always point `npm` at my branch if absolutely necessary, but it would be nice to figure out in what ways these route/function names might evolve before that.

**Comment by gr2m** [comment]
> it would be nice to figure out in what ways these route/function names might evolve before that

I was thinking about the naming yesterday. Looking at the conventions of the other method names (see #889) I’m tending towards

- `octokit.migrations.startForOrg()` for the organization (https://developer.github.com/v3/migrations/orgs/#start-a-migration)
- `octokit.migrations.startForUser()` for the currently authenticated user

etc.

What do you think?

**Comment by sgvictorino** [comment]
@gr2m those names look good.

**Comment by bitsol** [comment]
@gr2m am I stretching the idea too far when I name a method this: `unlockRepoLockedForMigrationForOrg`? 😜

**Comment by bitsol** [comment]
Is that out of the scope of this PR, anyway? It looks like #889 will have all these changes.

**Comment by sgvictorino** [comment]
@gr2m is this out of the scope of the PR?
I ask because it looks like what's currently `migrations.unlockRepoLockedForMigration` would have to be renamed to `migrations.unlockRepo`, probably as part of #899, to prevent names like this: `unlockRepoLockedForMigrationForOrg`. 😄 
In other words, what changes should I make before #914 (this PR) can be merged, while making sure to contribute to the future of this library?
Thanks again!

**Comment by gr2m** [comment]
I’ll look more into it today and get back to you

**Comment by sgvictorino** [comment]
@gr2m why didn't the routes update automatically though?

**Comment by gr2m** [comment]
> why didn't the routes update automatically though?

The lib/routes.json file is not generated from ocotkit/routes, instead it’s matching the two based on the http verb + path. So if there are changes in the parameters or in the route description then lib/routes.json get updated automatically, but if there are entirely new routes nothing happens.

But that’s what https://github.com/octokit/rest.js/issues/889 is about, all these changes are coming from the method name being generated, too. So once we have that it should work all automatically, including adding new methods

**Pull request closed without merging**
