### PR TITLE
Mocha test path escaping

### PR DESCRIPTION
**Pull request by aryannarora**
On running `npm test` locally mocha is not able to find the test files. This is because the test path is given in single quotes in `package.json`. Replacing them with double quotes solved the error.

### CODE REVIEW

**Comment by gr2m** [comment]
that’s curious, I never run into this myself. What operation system / version are you running the tests on?

**Comment by aryannarora** [comment]
@gr2m Yes, i was curious too and then i found [this](https://github.com/mochajs/mocha/issues/2895), which made me open this pull request. 😆 
I'm using Windows 10 and mocha version is 5.0.4.

**Comment by gr2m** [comment]
Thanks a lot for doing the research :) Have you ever set up CI on windows before? I’ve only used travis so far but hear great things about https://github.com/marketplace/appveyor

**Review by gr2m — APPROVED** [review]

**Comment by aryannarora** [comment]
@gr2m Thanks for approving this change. 😄 
No, i have not set up any CI on windows ever but i'm surely gonna do soon.

**Comment by gr2m** [comment]
please let me know how it goes :)

**Pull request merged**
