### PR TITLE
feat(multiple-assignees): Adding support for updating multiple assignees

### PR DESCRIPTION
**Pull request by burtonjc**
As per: https://developer.github.com/v3/issues/#create-an-issue
and: https://developer.github.com/v3/issues/#edit-an-issue

### CODE REVIEW

**Comment by kaizensoze** [comment]
The `assignees` param is preview only at the moment.

**Comment by burtonjc** [comment]
True, you just can't use `node-github` to update `assignees` without this change. Up to you though. No hard feelings if you don't want this in yet.

**Comment by kaizensoze** [comment]
I'm going to leave this out for now only because `node-github` doesn't handle preview stuff at the moment.

**Comment by burtonjc** [comment]
Cool, thanks for all the quick reviews!

**Pull request closed without merging**
