### PR TITLE
Support for ETAG

### PR DESCRIPTION
**Pull request by sielay**
Following PR is meant to allow it inject cache managing object, that would check, what was last ETAG value of specific response. This should help avoid exceeding quotas so easily.

This implementation is based on GitHub suggestion https://developer.github.com/v3/#conditional-requests

### CODE REVIEW

**Comment by WORMSS** [comment]
Why change all spaces for tabs?

**Comment by sielay** [comment]
Oh, sorry, in other projects I contribute they forced that. You mind it much?

**Comment by WORMSS** [comment]
Well, it is not my project to comment, but I was looking to see what the changes were, and noticed it was EVERY LINE had changed.. so from my point of view, I could not see the proper changes.

**Comment by jerone** [comment]
This will show all _real_ changes: https://github.com/mikedeboer/node-github/pull/255/files?w=1
But the style :art: changes should really be reverted.

**Comment by WORMSS** [comment]
Thank you @jerone,
@sielay I like how the etag handler is external. I had tried to work with `node-github-cache` before and that had modules that required compiling which made it a no go as it had to "just work" on windows, without making sure the user had visual studio and python and gcc and a bunch of other things installed on their machine. So I tip my hat to you good sir.

**Comment by sielay** [comment]
I read it as positive comment @WORMSS . I will cleanup that over the weekend and let you know.

**Comment by kaizensoze** [comment]
I'd be open to merging this once all conflicts are resolved and whitespace changes undone.

**Comment by kaizensoze** [comment]
I'm going to close this only because the codebase has changed so much since the PR was introduced.

**Comment by gr2m** [comment]
I can’t give an estimate, but I will revise the topic of caching some time soon. You can also follow #620 if you are interested in progress on this library in general

**Comment by jsg2021** [comment]
I think #673 covers this

**Comment by jsg2021** [comment]
See this line: 

https://github.com/octokit/node-github/blob/master/test/integration/conditional-request-test.js#L21

**Comment by gr2m** [comment]
Yeah I think that should work as a workaround for the time beeing.

I don’t want to put caching into `@octokit/rest.js` core, but I want to make it a first-class API / plugin, but can’t give an ETA on that yet

**Pull request closed without merging**
