### PR TITLE
Add parameters available for preview, from create deployment status endpoint

### PR DESCRIPTION
**Pull request by roonyh**

### CODE REVIEW

**Comment by kaizensoze** [comment]
I think it's two different endpoints that are missing params:

```
create-deployment
  transient_environment
  production_environment

create-deployment-status
  log_url
  environment_url
  auto_inactive
```

https://developer.github.com/v3/repos/deployments/

**Comment by roonyh** [comment]
@kaizensoze Got it. Will add those too.

**Comment by kaizensoze** [comment]
Sorry I didn't take a close enough look at the diff. It looked like those params were being added for createDeployment. You can add the params for the other endpoint as a separate PR if you want.

**Comment by kaizensoze** [comment]
This looks good. I'm going to merge it as is for the one endpoint.

**Pull request merged**
