### PR TITLE
Set error.headers if present

### LINKED ISSUE #791: Recursive octokit.getNextPage(response) omits headers
Hey @gr2m !

I updated from `14.0.9` to `15.1.7` and noticed that headers are missing in the error.

Sample code am using
```javascript
  try {
    let response = await octokit.repos.getForOrg({
      org: 'octokit',
      type: 'public',
    })
    var { data } = response;
    while (octokit.hasNextPage(response)) {
      response = await octokit.getNextPage(response)
      data = data.concat(response.data)
    }
  } catch (error) {
    if (error.code === 403) {
      console.log(error);
      console.log(error.headers); // fails here...
    }
  }

```

I saw a simmilar issue being reported here https://github.com/octokit/rest.js/issues/706, solved here https://github.com/octokit/rest.js/pull/707 and released here https://github.com/octokit/rest.js/releases/tag/v14.0.4

Let me know if you need more info or I can be of any help in fixing this one 😄

### PR DESCRIPTION
**Pull request by gr2m**
fixes #791

### CODE REVIEW

**Comment by cg-cnu** [comment]
Hey @gr2m I tried to test the code but couldn't figure out a way to get the changes made in this commit to my local project. I do read `contributing.md` and `HOW_IT_WORKS.md` but couldn't figure out this specific step. Sorry for bothering but would you mind explain the process ? Thanks for your time 🙂

**Comment by gr2m** [comment]
No problem, happy to help.

You can do 

```
npm install octokit/rest.js#791/error-headers
```

`octokit/rest.js` is the github repository, `791/error-headers` is the branch you want to install (if you leave it out it’s `master`).

That should do the trick. You can double check with `npm ls @octokit/rest` which will show something like 

```
└── @octokit/rest@0.0.0-semantically-released  (git+https://github.com/octokit/rest.js.git#505ed1f57671480b625131abb00c277c67cae40a)
```

Once you are done testing, you can install `@octokit/rest` from npm again, with `npm i @octokit/rest`

Does that work for you?

**Comment by cg-cnu** [comment]
Hey Gregor!
Thanks so much for the detailed explanation. Yes, that did helped me test out and I can confirm that the issue is fixed. 😄

**Comment by cg-cnu** [comment]
Hey @gr2m Wondering if you want to add the above debugging steps to `CONTRIBUTING.md` so that other can benefit from it and you don't have to repeat it again ?

**Comment by gr2m** [comment]
That’s a nice idea :) Could you send a follow up PR for that?

Thanks for testing the PR 👍

**Pull request merged**
