### PR TITLE
Add CodeQL security scanning

### PR DESCRIPTION
**Pull request by jhutchings1**
Hi, I'm a PM on the GitHub security team. This repository is eligible to try the new [GitHub Advanced Security code scanning](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning) beta.

Code scanning runs a static analysis tool called CodeQL which scans your code at build time to find any potential security issues. We've tuned the set of queries to be only the most severe, most precise issues. We'll show alerts in the security tab, and we'll show alerts for any net new vulnerabilities on pull requests as well. We've tried to make this super developer friendly, but we'd love your feedback as we work through the beta. 

If you're interested in trying it out, you can merge this pull request to set up the Actions workflow.

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
Oh snap! Thanks Justin! Excited to try it out!

Note that while `@octokit/rest` is the most widely used JS Octokit library right now, it's only a few lines of code: https://github.com/octokit/rest.js/blob/master/src/index.ts

I wonder if you could also enable the underlying core libraries:

- [x] [octokit/core.js](https://github.com/octokit/core.js)
- [x] [octokit/auth-token.js](https://github.com/octokit/auth-token.js)
- [x] [octokit/graphql.js](https://github.com/octokit/graphql.js)
- [x] [octokit/request.js](https://github.com/octokit/request.js)
- [x] [octokit/endpoint.js](https://github.com/octokit/endpoint.js)
- [x] [octokit/request-error.js](https://github.com/octokit/request-error.js)
- [x] [octokit/types.ts](https://github.com/octokit/types.ts)
- [x] [octokit/plugin-paginate-rest.js](https://github.com/octokit/plugin-paginate-rest.js)
- [x] [octokit/plugin-request-log.js](https://github.com/octokit/plugin-request-log.js)
- [x] [octokit/plugin-rest-endpoint-methods.js](https://github.com/octokit/plugin-rest-endpoint-methods.js)

**Comment by jhutchings1** [comment]
@gr2m You bet! Let me run my PR creation script to get things kicked off for each of those as well!

**Comment by gr2m** [comment]
@jhutchings1 I think you missed https://github.com/octokit/request.js :)

**Comment by jhutchings1** [comment]
@gr2m You're right, I did! I just kicked it again, so you should have the PR now

**Comment by gr2m** [comment]
Hey @jhutchings1 I get a lot of false positives because of code that is run in tests. Can I configure the `paths-ignore` option in the action workflow?

**Comment by jhutchings1** [comment]
@gr2m Kind of. CodeQL doesn't pay attention to the Actions `paths-ignore` statement, but you can specify one to it using a configuration file. [Documentation here](https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#specifying-directories-to-scan). Hope that helps!

**Comment by gr2m** [comment]
@jhutchings1 I have the CodeQL action failing with this error

> No SARIF files found to upload in "../results".

https://github.com/octokit/auth-unauthenticated.js/actions/runs/194325150

Might this be a regression with the new Action runner relaesed today?

**Comment by robertbrignull** [comment]
Pretty sure this wasn't a regression with the action runner. The root cause was the codeql action not being able to detect which languages to analyze because there wasn't yet any code on the default branch. You'll see the action is running successfully now that you've merged that branch in.

Obviously we were doing a pretty poor job of reporting that error to you. I've opened https://github.com/github/codeql-action/pull/131 to improve the error message in this case so hopefully it'll be slightly more clear what the reason is.

**Comment by gr2m** [comment]
Thanks!

**Pull request merged**
