### PR TITLE
Proxy issue

### PR DESCRIPTION
**Pull request by ludovicderochethales**
Hello,

We've got an issue when using your library behind a corporate proxy. I fixed it using https-proxy-agent.
If you want to integrate in your version, feel free to do it :)

Thanks for your awesome work by the way!

### CODE REVIEW

**Comment by zewa666** [comment]
Please validate and merge this PR as this turns out to be a show-stopping problem for users sitting behind a corporate proxy.

@ludovicderochethales thanks for your contribution it works and helped a lot for the aurelia generator :+1:

**Comment by ludovicderochethales** [comment]
@zewa666 You're welcome! :)

**Comment by mhsu0020** [comment]
Can someone merge this pull request? I want to use Atom-sync-settings behind our corporate proxy :)

**Comment by kaizensoze** [comment]
Included in [kaizensoze/node-github](https://github.com/kaizensoze/node-github) repo which has recently been merged into upstream.

**Pull request closed without merging**
