### PR TITLE
Updated getForUser for Organizations

### PR DESCRIPTION
**Pull request by leroyjware**
- Update getForUser to use /user/orgs rather than /users/:user/orgs

### CODE REVIEW

**Comment by leroyjware** [comment]
I had to update this in my node_modules folder to list my organizations. Is this a bug?

**Comment by kaizensoze** [comment]
There's `users.get-orgs`, which corresponds to `/user/orgs`, and then there's `orgs.get-for-user` which corresponds to `/users/:user/orgs`. Technically `users.get-orgs` should be under orgs if you were strictly mapping to the github api docs (https://developer.github.com/v3/orgs/), which this api does for the most part, with `users.get-orgs` being an exception, because the `*-for-user` endpoints map to `/users/:user/*`, but in this case it's `/user/orgs` so if you moved it it would be `orgs.get-orgs` which doesn't make as much sense semantically. _However_, I do see that the descriptions for both `users.get-orgs` and `orgs.get-for-user` need to be changed to avoid additional confusion. Namely:

```
users.get-orgs
Get your organizations -> List organizations for the authenticated user.
```

```
orgs.get-for-user
List user's organizations -> List public organization memberships for the specified user.
```

Does that make sense?

**Comment by leroyjware** [comment]
Just tested users.getOrgs. That worked. I appreciate it. I'll close this.

**Comment by kaizensoze** [comment]
Cool, I'll reference this issue when fixing the descriptions. Is the orgs.getForUser endpoint not working for you though?

**Comment by leroyjware** [comment]
Yea, looks like something changed on Github. When I look at the documentation, Github is using /user/orgs: https://developer.github.com/v3/orgs/#list-your-organizations

I could have also probably solved by using /v3. I didn't try that either.

**Comment by kaizensoze** [comment]
Right, but there's also https://developer.github.com/v3/orgs/#list-user-organizations further down. You just need to provide a username since it's not for the authenticated user.

**Comment by kaizensoze** [comment]
I should really add a getUserOrgs example though using both endpoints.

**Comment by kaizensoze** [comment]
Added example: https://github.com/mikedeboer/node-github/blob/master/examples/getUserOrgs.js

You don't have to specify the version since it defaults to the latest (v3).

**Comment by leroyjware** [comment]
Nice. Thanks! :)

**Pull request closed without merging**
