### PR TITLE
added support to releases#get-latest for github api v3

### PR DESCRIPTION
**Pull request by marcos-abreu**
added support to releases#getLatest - for api v3
github api ref: https://developer.github.com/v3/repos/releases/#get-the-latest-release

### CODE REVIEW

**Comment by dcarroll** [comment]
Would love to see this merged in.

**Comment by kaizensoze** [comment]
This repo is dead. I forked it and applied a bunch of PRs here: https://github.com/kaizensoze/node-github

getLatestRelease: https://kaizensoze.github.io/node-github/#api-repos-getLatestRelease

**Comment by dcarroll** [comment]
Ah, noted, and thanks!

Dave Carroll

On Feb 2, 2016, at 7:25 PM, Joe Gallo notifications@github.com wrote:

This repo is dead. I forked it and applied a bunch of PRs here:
https://github.com/kaizensoze/node-github

getLatestRelease:
https://kaizensoze.github.io/node-github/#api-repos-getLatestRelease

**Comment by rgbkrk** [comment]
Thanks @kaizensoze, checking that out now.

**Comment by kaizensoze** [comment]
The fork has been merged into upstream

https://mikedeboer.github.io/node-github/#api-repos-getLatestRelease

**Pull request closed without merging**
