### PR TITLE
Added a TypeScript generator

### LINKED ISSUE #337: Add TypeScript definition file
Do you have any plans to provide a TypeScript definition file for your library? which is, btw, awesome.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #337.

This PR generalizes the Flow declaration generator to a TypeScript one so that TypeScript users can also benefit. Most of the code was unmodified, but I customized the template file to operate better for TypeScript consumers.

### CODE REVIEW

**Comment by ludohenin** [comment]
Looks awesome.

**Comment by kaizensoze** [comment]
Awesome, thanks!

**Comment by julien-c** [comment]
nice! Any way you can push a release in the next couple of days?

**Comment by jessehouwing** [comment]
Got 3 compile errors when using typescript 2.1.4.
```
node_modules/github/lib/index.d.ts(1328,18): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
node_modules/github/lib/index.d.ts(1413,19): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
node_modules/github/lib/index.d.ts(1420,19): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
```
In all cases it was fixed by replacing `Array` with `Array<string>` or `string[]`

**Review by jessehouwing — COMMENTED** [review]
probably needs "reviewers" and "comments" to map to string[] as well.

**Pull request merged**
