### PR TITLE
Fix various documentation nits

### PR DESCRIPTION
**Pull request by srawlins**
* ~Fix missing whitespace, eaten by React~

  Edit: This fix was lost in a rebase; perhaps fixed on master.

  Fixes:
  Screen Shot 2020-02-17 at 11 20 24 AM
  (This `{" "}` trick is used elsewhere in `endpoint.js`.)

* Remove unwarranted code formatting on text; add period. Fixes:
  Screen Shot 2020-02-17 at 11 19 16 AM
* Remove duplicate periods. Fixes:
  Screen Shot 2020-02-17 at 11 22 16 AM

-----
[View rendered docs/src/pages/api/00_usage.md](https://github.com/srawlins/rest.js/blob/documentation-nits/docs/src/pages/api/00_usage.md)

### CODE REVIEW

**Comment by gr2m** [comment]
Hey Sam, I very much appreciate your pull request!

We have a new version coming up that changes a lot of the internal implementation of the code: #1598. We also have a pending pull request for the docs specifically #1596, I'm not sure if the changes there conflict with yours?

The update to the TypeScript would need to go here: https://github.com/octokit/plugin-rest-endpoint-methods.js/

For the docs update, I'd hold off until we merge #1596, if that's okay? 

I'd recommend to create an issue first next time so I can safe you some time

**Comment by srawlins** [comment]
> We also have a pending pull request for the docs specifically #1596, I'm not sure if the changes there conflict with yours?

I'll Subscribe to #1596 and wait and rebase.

> The update to the TypeScript would need to go here: https://github.com/octokit/plugin-rest-endpoint-methods.js/

Thanks!

> For the docs update, I'd hold off until we merge #1596, if that's okay?

SG.

> I'd recommend to create an issue first next time so I can safe you some time

Haha sorry I saw them while reading the docs and couldn't resist! Thanks for the tip though.

**Comment by srawlins** [comment]
I see #1596 was merged into `beta`. Should I re-open the applicable parts of this PR against `beta`? Or wait (for #1598 ?) until `beta` is merged into `master`?

**Comment by gr2m** [comment]
Wait for https://github.com/octokit/rest.js/pull/1619, I'm planning on merging it tomorrow

**Comment by gr2m** [comment]
#1619 is merged. Can you rebase your work on latest master?

**Comment by srawlins** [comment]
Okie doke; pushed the TS changes at https://github.com/octokit/plugin-rest-endpoint-methods.js/pull/46 .

**Comment by srawlins** [comment]
Rebased!

**Review by gr2m — APPROVED** [review]
Thanks a lot!

**Pull request merged**
