### PR TITLE
add support to allow api stuff under preview period

### PR DESCRIPTION
**Pull request by kaizensoze**
Add possible accept headers for features currently under preview period
and allow user to include them by including an includePreview config var
set to true.

### CODE REVIEW

**Comment by kaizensoze** [comment]
```
application/vnd.github.cerberus-preview       (multiple issue assignees)
application/vnd.github.mockingbird-preview    (timeline)
application/vnd.github.squirrel-girl-preview  (reactions)
application/vnd.github.barred-rock-preview    (source import)
application/vnd.github.damage-preview         (oauth application authorizations changes)
application/vnd.github.ant-man-preview+json   (deployment additional stuff)
application/vnd.github.cryptographer-preview  (gpg stuff)
application/vnd.github.polaris-preview        (squash pull request)
```

**Comment by codydaig** [comment]
LGTM

**Comment by 2heal** [comment]
I have been inundated with items-no doubt all good-however too much info-please remove me from list.  Thanks for your good work though.
Bithia

**Comment by kaizensoze** [comment]
@2heal This is something that **you** need to do: https://github.com/settings/notifications

**Comment by 2heal** [comment]
Thank you.  I did what was needed.  Good work as always.

**Pull request merged**
