### PR TITLE
Custom Accept header for checks APIs

### LINKED ISSUE #861: Custom Accept header not provided to Checks API
Using `@octokit/rest` version `15.4.0`, using [`checks.create`](https://github.com/octokit/rest.js/blob/b716c30ff1ed78b16813cb094bcc2c80445cee05/lib/routes.json#L997), the [custom `Accept` header](https://developer.github.com/changes/#how-can-i-try-it) (`application/vnd.github.antiope-preview+json`) isn't provided, resulting in an error in the following code:

```javascript
octokit.checks.create({
  owner: 'swinton',
  repo: 'example',
  name: 'feedback',
  head_branch: 'helloworld',
  head_sha: '2e3d00a6f14a667d50ad9ccd6f3dcfded52121e2',
  status: 'in_progress',
  started_at: (new Date()).toISOString(),  // The time that the check run began in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`
  completed_at: (new Date()).toISOString(),
  conclusion: 'status'
})
```

The error returned is:

> If you would like to help us test the Checks API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.

It would be nice if the accept header was included by default :bow:

### LINKED ISSUE #865: When authenticated as integration, accept header gets always set to application/vnd.github.machine-man-preview+json
follow up for #864 

https://github.com/octokit/rest.js/blob/72bd9afe7c8eb0a82fef3f229d5ab6c75d04f112/lib/plugins/authentication/before-request.js#L21-L25

It should amend the accept header, multiple accept headers can be passed, separated by commas

### PR DESCRIPTION
**Pull request by gr2m**
fixes #861 

### TODOs

- fix #865, then remove `application/vnd.github.machine-man-preview+json` from default headers

### CODE REVIEW

**Comment by gr2m** [comment]
@swinton I created a test to make sure that you can set custom accept headers with both `{headers: {Accept: '...'}}` and `{headers: {accept: '...'}}` and couldn’t find a problem there. You mentioned that this didn’t work for you?

I’m now adding the default preview header to the new checks routes so this becomes a non-issue, but still wanted to check on the custom header setting because that needs to work for other use cases

**Comment by gr2m** [comment]
@swinton @monder can you check if this PR fixes the problem for you?

**Comment by monder** [comment]
@gr2m I've checked my issue and everything works perfectly, but I'm always setting the header. Issue 
https://github.com/octokit/rest.js/issues/860 is fixed in 15.4.1. Thanks for the quick response.
@swinton Indeed, its a bit confusing and took me a couple of hours to realize that these tokens are not the same. You can only use `integration` with [Apps api](https://octokit.github.io/rest.js/#api-Apps).
Basically you have to do something like this:
```javascript
const githubToken = jwt.sign({
    iat: Math.floor(Date.now() / 1000),
    exp: Math.floor(Date.now() / 1000) + 9 * 60,
    iss: `${config.github.iss}`,
}, config.github.key, { algorithm: 'RS256' });

octokit.authenticate({
    type: 'integration',
    token: githubToken,
});

const tokenResult = await octokit.apps.createInstallationToken({installation_id: config.github.installation_id})
octokit.authenticate({
    type: 'token',
    token: tokenResult.data.token,
});

const body = {
    owner: 'monder',
    repo: 'experiments',
    head_branch: 'master',
    head_sha: '308ccfb77bb12024e1ea69f61374b3051f13cf71',
    name: 'test_check',
    status: 'completed',
    completed_at: new Date().toISOString(),
    conclusion: 'failure',
    output: {
        title: 'Failure',
        summary: '',
        annotations: [{
            filename: 'README.md',
            blob_href: `https://github.com/monder/experiments/blob/308ccfb77bb12024e1ea69f61374b3051f13cf71/README.md`,
            warning_level: 'failure',
            message: 'message text',
            start_line: 2,
            end_line: 2,
        }],
    },
};

const res = await octokit.checks.create({
    ...body,
    headers: {
        accept: 'application/vnd.github.antiope-preview+json'
    }
});
```
Note that the differ `installation_id` from `iss` and in my case I didn't want to waste api calls so I just hardcoded it for our organisation.
And also FYI, annotations do not show up on github when viewing PR in `split` mode, only `unified` view works for now.

**Comment by swinton** [comment]
> you can set custom accept headers with both {headers: {Accept: '...'}} and {headers: {accept: '...'}} and couldn’t find a problem there. You mentioned that this didn’t work for you?

This is working for me now, thanks to [the guidance](https://github.com/octokit/rest.js/pull/864#issuecomment-388488189) from @monder 

Basically, in [my code above](https://github.com/octokit/rest.js/pull/864#issuecomment-388469653), I was passing the wrong authentication type (`integration` instead of `token` 🤦‍♂️) I changed that and it works :tada:

**Pull request merged**
