### PR TITLE
Use standard

### PR DESCRIPTION
**Pull request by zeke**
This PR updates the codebase to use [standard](http://ghub.io/standard)-style JavaScript.

Notes:

- Added `standard` and `standard-markdown` which lints js snippets in markdown files.
- Added linting as part of `npm test` script to maintain consistency moving forward.
- Auto-fixed a bunch of stuff with `standard --fix`
- Hand-fixed the rest.
- Sprinkled `eslint-disable` in a handful of places to avoid breaking anything.

cc @gr2m @bkeepers @feross

### CODE REVIEW

**Comment by gr2m** [comment]
thanks @zeke, but I want to review the open pull requests first before adapting standard

**Comment by zeke** [comment]
No worries. I figured it was manageable now since there are only three open PRs.

**Review by gr2m — APPROVED** [review]
Thanks @zeke 👍

**Comment by zeke** [comment]
🙌

**Pull request merged**
