### PR TITLE
Fixes typescript bindings

### PR DESCRIPTION
**Pull request by jessehouwing**
This change is [Reviewable](https://reviewable.io/reviews/mikedeboer/node-github/482)

### CODE REVIEW

**Comment by kaizensoze** [comment]
I'm not too familiar with typescript. What do I need to do to test this? Running `tsc index.d.ts` produces the following output:

```
index.d.ts(22,22): error TS2304: Cannot find name 'Promise'.
index.d.ts(1328,18): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
index.d.ts(1413,19): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
index.d.ts(1420,19): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
index.d.ts(2523,63): error TS2304: Cannot find name 'Promise'.
index.d.ts(2524,98): error TS2304: Cannot find name 'Promise'.
index.d.ts(2526,67): error TS2304: Cannot find name 'Promise'.
index.d.ts(2527,102): error TS2304: Cannot find name 'Promise'.
index.d.ts(2529,63): error TS2304: Cannot find name 'Promise'.
index.d.ts(2530,98): error TS2304: Cannot find name 'Promise'.
index.d.ts(2532,64): error TS2304: Cannot find name 'Promise'.
index.d.ts(2533,99): error TS2304: Cannot find name 'Promise'.
index.d.ts(2536,89): error TS2304: Cannot find name 'Promise'.
index.d.ts(2537,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2538,93): error TS2304: Cannot find name 'Promise'.
index.d.ts(2539,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2540,77): error TS2304: Cannot find name 'Promise'.
index.d.ts(2541,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2542,131): error TS2304: Cannot find name 'Promise'.
index.d.ts(2543,159): error TS2304: Cannot find name 'Promise'.
index.d.ts(2544,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2545,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2546,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2547,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2548,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2551,84): error TS2304: Cannot find name 'Promise'.
index.d.ts(2552,98): error TS2304: Cannot find name 'Promise'.
index.d.ts(2553,110): error TS2304: Cannot find name 'Promise'.
index.d.ts(2554,112): error TS2304: Cannot find name 'Promise'.
index.d.ts(2555,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2556,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2557,112): error TS2304: Cannot find name 'Promise'.
index.d.ts(2558,98): error TS2304: Cannot find name 'Promise'.
index.d.ts(2559,110): error TS2304: Cannot find name 'Promise'.
index.d.ts(2560,104): error TS2304: Cannot find name 'Promise'.
index.d.ts(2561,43): error TS2304: Cannot find name 'Promise'.
index.d.ts(2562,98): error TS2304: Cannot find name 'Promise'.
index.d.ts(2563,112): error TS2304: Cannot find name 'Promise'.
index.d.ts(2564,112): error TS2304: Cannot find name 'Promise'.
index.d.ts(2565,126): error TS2304: Cannot find name 'Promise'.
index.d.ts(2566,108): error TS2304: Cannot find name 'Promise'.
index.d.ts(2567,122): error TS2304: Cannot find name 'Promise'.
index.d.ts(2568,136): error TS2304: Cannot find name 'Promise'.
index.d.ts(2569,132): error TS2304: Cannot find name 'Promise'.
index.d.ts(2570,138): error TS2304: Cannot find name 'Promise'.
index.d.ts(2571,106): error TS2304: Cannot find name 'Promise'.
index.d.ts(2572,110): error TS2304: Cannot find name 'Promise'.
index.d.ts(2573,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2574,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2575,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2576,86): error TS2304: Cannot find name 'Promise'.
index.d.ts(2577,102): error TS2304: Cannot find name 'Promise'.
index.d.ts(2578,110): error TS2304: Cannot find name 'Promise'.
index.d.ts(2579,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2580,104): error TS2304: Cannot find name 'Promise'.
index.d.ts(2581,104): error TS2304: Cannot find name 'Promise'.
index.d.ts(2582,88): error TS2304: Cannot find name 'Promise'.
index.d.ts(2585,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2586,75): error TS2304: Cannot find name 'Promise'.
index.d.ts(2587,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2588,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2589,69): error TS2304: Cannot find name 'Promise'.
index.d.ts(2590,85): error TS2304: Cannot find name 'Promise'.
index.d.ts(2591,75): error TS2304: Cannot find name 'Promise'.
index.d.ts(2592,71): error TS2304: Cannot find name 'Promise'.
index.d.ts(2593,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2594,71): error TS2304: Cannot find name 'Promise'.
index.d.ts(2595,75): error TS2304: Cannot find name 'Promise'.
index.d.ts(2596,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2597,71): error TS2304: Cannot find name 'Promise'.
index.d.ts(2598,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2599,75): error TS2304: Cannot find name 'Promise'.
index.d.ts(2600,85): error TS2304: Cannot find name 'Promise'.
index.d.ts(2601,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2602,89): error TS2304: Cannot find name 'Promise'.
index.d.ts(2603,85): error TS2304: Cannot find name 'Promise'.
index.d.ts(2604,89): error TS2304: Cannot find name 'Promise'.
index.d.ts(2607,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2608,85): error TS2304: Cannot find name 'Promise'.
index.d.ts(2609,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2610,89): error TS2304: Cannot find name 'Promise'.
index.d.ts(2611,125): error TS2304: Cannot find name 'Promise'.
index.d.ts(2612,89): error TS2304: Cannot find name 'Promise'.
index.d.ts(2613,91): error TS2304: Cannot find name 'Promise'.
index.d.ts(2614,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2615,95): error TS2304: Cannot find name 'Promise'.
index.d.ts(2616,95): error TS2304: Cannot find name 'Promise'.
index.d.ts(2617,95): error TS2304: Cannot find name 'Promise'.
index.d.ts(2618,77): error TS2304: Cannot find name 'Promise'.
index.d.ts(2619,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2620,119): error TS2304: Cannot find name 'Promise'.
index.d.ts(2621,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2622,85): error TS2304: Cannot find name 'Promise'.
index.d.ts(2625,102): error TS2304: Cannot find name 'Promise'.
index.d.ts(2626,116): error TS2304: Cannot find name 'Promise'.
index.d.ts(2627,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2628,124): error TS2304: Cannot find name 'Promise'.
index.d.ts(2629,112): error TS2304: Cannot find name 'Promise'.
index.d.ts(2630,122): error TS2304: Cannot find name 'Promise'.
index.d.ts(2633,76): error TS2304: Cannot find name 'Promise'.
index.d.ts(2634,84): error TS2304: Cannot find name 'Promise'.
index.d.ts(2635,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2636,84): error TS2304: Cannot find name 'Promise'.
index.d.ts(2637,70): error TS2304: Cannot find name 'Promise'.
index.d.ts(2638,76): error TS2304: Cannot find name 'Promise'.
index.d.ts(2639,72): error TS2304: Cannot find name 'Promise'.
index.d.ts(2640,72): error TS2304: Cannot find name 'Promise'.
index.d.ts(2641,76): error TS2304: Cannot find name 'Promise'.
index.d.ts(2642,88): error TS2304: Cannot find name 'Promise'.
index.d.ts(2643,90): error TS2304: Cannot find name 'Promise'.
index.d.ts(2644,102): error TS2304: Cannot find name 'Promise'.
index.d.ts(2645,112): error TS2304: Cannot find name 'Promise'.
index.d.ts(2646,86): error TS2304: Cannot find name 'Promise'.
index.d.ts(2647,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2648,84): error TS2304: Cannot find name 'Promise'.
index.d.ts(2649,90): error TS2304: Cannot find name 'Promise'.
index.d.ts(2650,86): error TS2304: Cannot find name 'Promise'.
index.d.ts(2651,90): error TS2304: Cannot find name 'Promise'.
index.d.ts(2652,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2653,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2654,80): error TS2304: Cannot find name 'Promise'.
index.d.ts(2655,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2656,80): error TS2304: Cannot find name 'Promise'.
index.d.ts(2657,86): error TS2304: Cannot find name 'Promise'.
index.d.ts(2658,86): error TS2304: Cannot find name 'Promise'.
index.d.ts(2659,86): error TS2304: Cannot find name 'Promise'.
index.d.ts(2660,92): error TS2304: Cannot find name 'Promise'.
index.d.ts(2661,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2662,86): error TS2304: Cannot find name 'Promise'.
index.d.ts(2663,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2664,94): error TS2304: Cannot find name 'Promise'.
index.d.ts(2665,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2666,90): error TS2304: Cannot find name 'Promise'.
index.d.ts(2667,88): error TS2304: Cannot find name 'Promise'.
index.d.ts(2668,94): error TS2304: Cannot find name 'Promise'.
index.d.ts(2669,94): error TS2304: Cannot find name 'Promise'.
index.d.ts(2670,94): error TS2304: Cannot find name 'Promise'.
index.d.ts(2671,98): error TS2304: Cannot find name 'Promise'.
index.d.ts(2674,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2675,94): error TS2304: Cannot find name 'Promise'.
index.d.ts(2676,104): error TS2304: Cannot find name 'Promise'.
index.d.ts(2677,114): error TS2304: Cannot find name 'Promise'.
index.d.ts(2678,112): error TS2304: Cannot find name 'Promise'.
index.d.ts(2679,124): error TS2304: Cannot find name 'Promise'.
index.d.ts(2680,90): error TS2304: Cannot find name 'Promise'.
index.d.ts(2681,102): error TS2304: Cannot find name 'Promise'.
index.d.ts(2682,92): error TS2304: Cannot find name 'Promise'.
index.d.ts(2683,112): error TS2304: Cannot find name 'Promise'.
index.d.ts(2684,110): error TS2304: Cannot find name 'Promise'.
index.d.ts(2685,112): error TS2304: Cannot find name 'Promise'.
index.d.ts(2686,106): error TS2304: Cannot find name 'Promise'.
index.d.ts(2687,92): error TS2304: Cannot find name 'Promise'.
index.d.ts(2690,44): error TS2304: Cannot find name 'Promise'.
index.d.ts(2691,56): error TS2304: Cannot find name 'Promise'.
index.d.ts(2692,102): error TS2304: Cannot find name 'Promise'.
index.d.ts(2693,46): error TS2304: Cannot find name 'Promise'.
index.d.ts(2694,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2695,90): error TS2304: Cannot find name 'Promise'.
index.d.ts(2696,90): error TS2304: Cannot find name 'Promise'.
index.d.ts(2697,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2698,42): error TS2304: Cannot find name 'Promise'.
index.d.ts(2699,47): error TS2304: Cannot find name 'Promise'.
index.d.ts(2702,74): error TS2304: Cannot find name 'Promise'.
index.d.ts(2703,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2704,68): error TS2304: Cannot find name 'Promise'.
index.d.ts(2705,74): error TS2304: Cannot find name 'Promise'.
index.d.ts(2706,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2707,92): error TS2304: Cannot find name 'Promise'.
index.d.ts(2708,86): error TS2304: Cannot find name 'Promise'.
index.d.ts(2709,94): error TS2304: Cannot find name 'Promise'.
index.d.ts(2710,104): error TS2304: Cannot find name 'Promise'.
index.d.ts(2711,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2712,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2713,94): error TS2304: Cannot find name 'Promise'.
index.d.ts(2714,94): error TS2304: Cannot find name 'Promise'.
index.d.ts(2715,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2716,102): error TS2304: Cannot find name 'Promise'.
index.d.ts(2717,108): error TS2304: Cannot find name 'Promise'.
index.d.ts(2718,112): error TS2304: Cannot find name 'Promise'.
index.d.ts(2719,130): error TS2304: Cannot find name 'Promise'.
index.d.ts(2720,78): error TS2304: Cannot find name 'Promise'.
index.d.ts(2721,76): error TS2304: Cannot find name 'Promise'.
index.d.ts(2722,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2723,78): error TS2304: Cannot find name 'Promise'.
index.d.ts(2724,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2725,90): error TS2304: Cannot find name 'Promise'.
index.d.ts(2726,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2727,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2728,102): error TS2304: Cannot find name 'Promise'.
index.d.ts(2729,86): error TS2304: Cannot find name 'Promise'.
index.d.ts(2730,104): error TS2304: Cannot find name 'Promise'.
index.d.ts(2731,88): error TS2304: Cannot find name 'Promise'.
index.d.ts(2732,84): error TS2304: Cannot find name 'Promise'.
index.d.ts(2733,90): error TS2304: Cannot find name 'Promise'.
index.d.ts(2734,78): error TS2304: Cannot find name 'Promise'.
index.d.ts(2735,76): error TS2304: Cannot find name 'Promise'.
index.d.ts(2736,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2737,78): error TS2304: Cannot find name 'Promise'.
index.d.ts(2738,78): error TS2304: Cannot find name 'Promise'.
index.d.ts(2739,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2742,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2743,94): error TS2304: Cannot find name 'Promise'.
index.d.ts(2744,86): error TS2304: Cannot find name 'Promise'.
index.d.ts(2745,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2746,98): error TS2304: Cannot find name 'Promise'.
index.d.ts(2747,92): error TS2304: Cannot find name 'Promise'.
index.d.ts(2748,92): error TS2304: Cannot find name 'Promise'.
index.d.ts(2749,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2750,94): error TS2304: Cannot find name 'Promise'.
index.d.ts(2751,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2752,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2753,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2754,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2755,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2756,98): error TS2304: Cannot find name 'Promise'.
index.d.ts(2757,104): error TS2304: Cannot find name 'Promise'.
index.d.ts(2758,104): error TS2304: Cannot find name 'Promise'.
index.d.ts(2759,104): error TS2304: Cannot find name 'Promise'.
index.d.ts(2760,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2763,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2764,76): error TS2304: Cannot find name 'Promise'.
index.d.ts(2765,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2766,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2767,82): error TS2304: Cannot find name 'Promise'.
index.d.ts(2768,90): error TS2304: Cannot find name 'Promise'.
index.d.ts(2769,86): error TS2304: Cannot find name 'Promise'.
index.d.ts(2770,92): error TS2304: Cannot find name 'Promise'.
index.d.ts(2771,80): error TS2304: Cannot find name 'Promise'.
index.d.ts(2772,90): error TS2304: Cannot find name 'Promise'.
index.d.ts(2773,88): error TS2304: Cannot find name 'Promise'.
index.d.ts(2774,106): error TS2304: Cannot find name 'Promise'.
index.d.ts(2775,94): error TS2304: Cannot find name 'Promise'.
index.d.ts(2776,94): error TS2304: Cannot find name 'Promise'.
index.d.ts(2777,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2778,92): error TS2304: Cannot find name 'Promise'.
index.d.ts(2779,106): error TS2304: Cannot find name 'Promise'.
index.d.ts(2780,90): error TS2304: Cannot find name 'Promise'.
index.d.ts(2781,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2782,106): error TS2304: Cannot find name 'Promise'.
index.d.ts(2783,92): error TS2304: Cannot find name 'Promise'.
index.d.ts(2784,96): error TS2304: Cannot find name 'Promise'.
index.d.ts(2785,104): error TS2304: Cannot find name 'Promise'.
index.d.ts(2786,108): error TS2304: Cannot find name 'Promise'.
index.d.ts(2787,108): error TS2304: Cannot find name 'Promise'.
index.d.ts(2790,105): error TS2304: Cannot find name 'Promise'.
index.d.ts(2791,111): error TS2304: Cannot find name 'Promise'.
index.d.ts(2792,89): error TS2304: Cannot find name 'Promise'.
index.d.ts(2793,95): error TS2304: Cannot find name 'Promise'.
index.d.ts(2794,103): error TS2304: Cannot find name 'Promise'.
index.d.ts(2795,109): error TS2304: Cannot find name 'Promise'.
index.d.ts(2796,127): error TS2304: Cannot find name 'Promise'.
index.d.ts(2797,133): error TS2304: Cannot find name 'Promise'.
index.d.ts(2798,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2801,75): error TS2304: Cannot find name 'Promise'.
index.d.ts(2802,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2803,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2804,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2805,77): error TS2304: Cannot find name 'Promise'.
index.d.ts(2806,75): error TS2304: Cannot find name 'Promise'.
index.d.ts(2807,69): error TS2304: Cannot find name 'Promise'.
index.d.ts(2808,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2809,71): error TS2304: Cannot find name 'Promise'.
index.d.ts(2810,93): error TS2304: Cannot find name 'Promise'.
index.d.ts(2811,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2812,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2813,77): error TS2304: Cannot find name 'Promise'.
index.d.ts(2814,75): error TS2304: Cannot find name 'Promise'.
index.d.ts(2815,85): error TS2304: Cannot find name 'Promise'.
index.d.ts(2816,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2817,101): error TS2304: Cannot find name 'Promise'.
index.d.ts(2818,107): error TS2304: Cannot find name 'Promise'.
index.d.ts(2819,107): error TS2304: Cannot find name 'Promise'.
index.d.ts(2820,139): error TS2304: Cannot find name 'Promise'.
index.d.ts(2821,145): error TS2304: Cannot find name 'Promise'.
index.d.ts(2822,145): error TS2304: Cannot find name 'Promise'.
index.d.ts(2823,155): error TS2304: Cannot find name 'Promise'.
index.d.ts(2824,163): error TS2304: Cannot find name 'Promise'.
index.d.ts(2825,155): error TS2304: Cannot find name 'Promise'.
index.d.ts(2826,161): error TS2304: Cannot find name 'Promise'.
index.d.ts(2827,155): error TS2304: Cannot find name 'Promise'.
index.d.ts(2828,161): error TS2304: Cannot find name 'Promise'.
index.d.ts(2829,161): error TS2304: Cannot find name 'Promise'.
index.d.ts(2830,123): error TS2304: Cannot find name 'Promise'.
index.d.ts(2831,129): error TS2304: Cannot find name 'Promise'.
index.d.ts(2832,131): error TS2304: Cannot find name 'Promise'.
index.d.ts(2833,139): error TS2304: Cannot find name 'Promise'.
index.d.ts(2834,131): error TS2304: Cannot find name 'Promise'.
index.d.ts(2835,137): error TS2304: Cannot find name 'Promise'.
index.d.ts(2836,131): error TS2304: Cannot find name 'Promise'.
index.d.ts(2837,139): error TS2304: Cannot find name 'Promise'.
index.d.ts(2838,131): error TS2304: Cannot find name 'Promise'.
index.d.ts(2839,137): error TS2304: Cannot find name 'Promise'.
index.d.ts(2840,95): error TS2304: Cannot find name 'Promise'.
index.d.ts(2841,97): error TS2304: Cannot find name 'Promise'.
index.d.ts(2842,113): error TS2304: Cannot find name 'Promise'.
index.d.ts(2843,93): error TS2304: Cannot find name 'Promise'.
index.d.ts(2844,99): error TS2304: Cannot find name 'Promise'.
index.d.ts(2845,103): error TS2304: Cannot find name 'Promise'.
index.d.ts(2846,97): error TS2304: Cannot find name 'Promise'.
index.d.ts(2847,101): error TS2304: Cannot find name 'Promise'.
index.d.ts(2848,95): error TS2304: Cannot find name 'Promise'.
index.d.ts(2849,101): error TS2304: Cannot find name 'Promise'.
index.d.ts(2850,101): error TS2304: Cannot find name 'Promise'.
index.d.ts(2851,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2852,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2853,97): error TS2304: Cannot find name 'Promise'.
index.d.ts(2854,91): error TS2304: Cannot find name 'Promise'.
index.d.ts(2855,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2856,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2857,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2858,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2859,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2860,91): error TS2304: Cannot find name 'Promise'.
index.d.ts(2861,77): error TS2304: Cannot find name 'Promise'.
index.d.ts(2862,75): error TS2304: Cannot find name 'Promise'.
index.d.ts(2863,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2864,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2865,91): error TS2304: Cannot find name 'Promise'.
index.d.ts(2866,95): error TS2304: Cannot find name 'Promise'.
index.d.ts(2867,105): error TS2304: Cannot find name 'Promise'.
index.d.ts(2868,107): error TS2304: Cannot find name 'Promise'.
index.d.ts(2869,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2870,85): error TS2304: Cannot find name 'Promise'.
index.d.ts(2871,91): error TS2304: Cannot find name 'Promise'.
index.d.ts(2872,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2873,71): error TS2304: Cannot find name 'Promise'.
index.d.ts(2874,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2875,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2876,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2877,73): error TS2304: Cannot find name 'Promise'.
index.d.ts(2878,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2879,95): error TS2304: Cannot find name 'Promise'.
index.d.ts(2880,91): error TS2304: Cannot find name 'Promise'.
index.d.ts(2881,101): error TS2304: Cannot find name 'Promise'.
index.d.ts(2882,89): error TS2304: Cannot find name 'Promise'.
index.d.ts(2883,85): error TS2304: Cannot find name 'Promise'.
index.d.ts(2884,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2885,95): error TS2304: Cannot find name 'Promise'.
index.d.ts(2886,93): error TS2304: Cannot find name 'Promise'.
index.d.ts(2887,89): error TS2304: Cannot find name 'Promise'.
index.d.ts(2888,85): error TS2304: Cannot find name 'Promise'.
index.d.ts(2889,89): error TS2304: Cannot find name 'Promise'.
index.d.ts(2890,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2891,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2892,85): error TS2304: Cannot find name 'Promise'.
index.d.ts(2893,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2894,85): error TS2304: Cannot find name 'Promise'.
index.d.ts(2895,103): error TS2304: Cannot find name 'Promise'.
index.d.ts(2896,107): error TS2304: Cannot find name 'Promise'.
index.d.ts(2897,105): error TS2304: Cannot find name 'Promise'.
index.d.ts(2898,105): error TS2304: Cannot find name 'Promise'.
index.d.ts(2899,97): error TS2304: Cannot find name 'Promise'.
index.d.ts(2900,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2901,85): error TS2304: Cannot find name 'Promise'.
index.d.ts(2902,97): error TS2304: Cannot find name 'Promise'.
index.d.ts(2903,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2904,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2905,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2906,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2907,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2908,77): error TS2304: Cannot find name 'Promise'.
index.d.ts(2909,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2910,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2911,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2912,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2913,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2916,74): error TS2304: Cannot find name 'Promise'.
index.d.ts(2917,72): error TS2304: Cannot find name 'Promise'.
index.d.ts(2918,76): error TS2304: Cannot find name 'Promise'.
index.d.ts(2919,74): error TS2304: Cannot find name 'Promise'.
index.d.ts(2920,74): error TS2304: Cannot find name 'Promise'.
index.d.ts(2923,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2924,77): error TS2304: Cannot find name 'Promise'.
index.d.ts(2925,38): error TS2304: Cannot find name 'Promise'.
index.d.ts(2926,75): error TS2304: Cannot find name 'Promise'.
index.d.ts(2927,75): error TS2304: Cannot find name 'Promise'.
index.d.ts(2928,77): error TS2304: Cannot find name 'Promise'.
index.d.ts(2929,97): error TS2304: Cannot find name 'Promise'.
index.d.ts(2930,95): error TS2304: Cannot find name 'Promise'.
index.d.ts(2931,97): error TS2304: Cannot find name 'Promise'.
index.d.ts(2932,79): error TS2304: Cannot find name 'Promise'.
index.d.ts(2933,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2934,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2935,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2936,101): error TS2304: Cannot find name 'Promise'.
index.d.ts(2937,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2938,101): error TS2304: Cannot find name 'Promise'.
index.d.ts(2939,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2940,91): error TS2304: Cannot find name 'Promise'.
index.d.ts(2941,111): error TS2304: Cannot find name 'Promise'.
index.d.ts(2942,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2943,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2944,91): error TS2304: Cannot find name 'Promise'.
index.d.ts(2945,77): error TS2304: Cannot find name 'Promise'.
index.d.ts(2946,75): error TS2304: Cannot find name 'Promise'.
index.d.ts(2947,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2948,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2949,83): error TS2304: Cannot find name 'Promise'.
index.d.ts(2950,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2951,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2952,87): error TS2304: Cannot find name 'Promise'.
index.d.ts(2953,77): error TS2304: Cannot find name 'Promise'.
index.d.ts(2954,75): error TS2304: Cannot find name 'Promise'.
index.d.ts(2955,77): error TS2304: Cannot find name 'Promise'.
index.d.ts(2956,81): error TS2304: Cannot find name 'Promise'.
index.d.ts(2957,49): error TS2304: Cannot find name 'Promise'.
index.d.ts(2958,95): error TS2304: Cannot find name 'Promise'.
index.d.ts(2959,97): error TS2304: Cannot find name 'Promise'.
index.d.ts(2962,78): error TS2304: Cannot find name 'Promise'.
index.d.ts(2963,102): error TS2304: Cannot find name 'Promise'.
index.d.ts(2964,98): error TS2304: Cannot find name 'Promise'.
index.d.ts(2965,102): error TS2304: Cannot find name 'Promise'.
index.d.ts(2966,98): error TS2304: Cannot find name 'Promise'.
index.d.ts(2967,45): error TS2304: Cannot find name 'Promise'.
index.d.ts(2968,116): error TS2304: Cannot find name 'Promise'.
index.d.ts(2969,60): error TS2304: Cannot find name 'Promise'.
index.d.ts(2970,122): error TS2304: Cannot find name 'Promise'.
index.d.ts(2971,118): error TS2304: Cannot find name 'Promise'.
index.d.ts(2972,122): error TS2304: Cannot find name 'Promise'.
index.d.ts(2973,144): error TS2304: Cannot find name 'Promise'.
index.d.ts(2974,140): error TS2304: Cannot find name 'Promise'.
index.d.ts(2975,102): error TS2304: Cannot find name 'Promise'.
index.d.ts(2976,53): error TS2304: Cannot find name 'Promise'.
index.d.ts(2977,108): error TS2304: Cannot find name 'Promise'.
index.d.ts(2978,104): error TS2304: Cannot find name 'Promise'.
index.d.ts(2979,108): error TS2304: Cannot find name 'Promise'.
index.d.ts(2980,100): error TS2304: Cannot find name 'Promise'.
index.d.ts(2981,86): error TS2304: Cannot find name 'Promise'.
```

**Comment by jessehouwing** [comment]
You're missing the typescript bindings for `node` itself it seems... try running

```
npm install typescript@2.1.4
npm install @types/node
npm install @types/q
```

before trying to compile. 

And you need a `tsconfig.json` instructed to generate `es6` in your project root:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "rootDir": "./",
    "sourceMap": true
  },
  "include": ["node_modules/github/lib/index.d.ts"]
}
```

e.g.
```
\node_modules
    \github
        \lib
            \index.d.ts
\tsconfig.json
```

then call

```
tsc -p .
```
And you should end up with 0 errors

**Comment by jessehouwing** [comment]
(note that I'm a typescript fledgeling myself)

**Comment by kaizensoze** [comment]
Thanks, made some additional changes of Array -> string[] in index.d.ts and index.js.flow.

**Comment by justinfagnani** [comment]
@kaizensoze can we get a new release with these fixes? Thanks!

**Comment by kaizensoze** [comment]
@justinfagnani Sure, pushed as 7.2.1.

**Comment by justinfagnani** [comment]
@kaizensoze thanks!

**Pull request merged**
