### PR TITLE
remove getAllPages utility method

### LINKED ISSUE #350: github.getAllPages throws RangeError when rate limit exceeded
I am getting a `RangeError` (and thus stopping the whole app) when anonymously performing more than 60 requests per hour!

As soon as the time limitation passes everything is back to work again!

This is the stack trace: 

``` text
_http_server.js:192
    throw new RangeError(`Invalid status code: ${statusCode}`);
    ^

RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse.writeHead (/Users/renatoargh/Github/ghsummary/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:433:10)
```

### PR DESCRIPTION
**Pull request by kaizensoze**
I don't feel comfortable keeping this in here as it doesn't really go
with the other page-related methods. It's easier to just keep it
consistent and stick to hasNextPage/getNextPage.

resolves #350

### CODE REVIEW

**Comment by boneskull** [comment]
Hey, so this should have warranted a major version bump since it was a documented API.

**Comment by kaizensoze** [comment]
This hasn't been pushed to npm yet . My assumption was people not using releases or npm, and instead directly using the master branch, were to expect possible breaking changes. Is this an incorrect assumption?

**Comment by kaizensoze** [comment]
Bumped master to 2.0.0.

**Comment by boneskull** [comment]
@kaizensoze Sorry for the confusion.  What happened (I think) was this:
1.  `npm install github4`
2.  go to npmjs.com for README
3.  notice that `github4` had been merged back into `github`
4.  copy/paste from README: `npm install mikedeboer/node-github`  (whoops)
5.  notice the `getAllPages()` method is missing
6.  add comment in this issue

I had _intended_ to `npm install github`, but erroneously wound up with `master`.  Sorry for the confusion.

BTW, this method is very useful. 😛

**Comment by kaizensoze** [comment]
Ah ok. Yeah it is useful, but seemed to be causing confusion and didn't fit in well with the other page-related methods. I'll need to think about possibly refactoring it and adding it back in.

**Comment by boneskull** [comment]
I'm not a huge fan of the API, but rather the functionality it provides (or is intended to provide) reduces quite a bit of boilerplate.

**Pull request merged**
