### PR TITLE
Adding in the required field "enforce_admins"...

### LINKED ISSUE #536: updateBranchProtection now requires enforce_admins to be passed with it.
When calling updateBranchProtection, the api call fails now that enforce_admins is not in the outgoing response.  It is not a parameter I can add to the api object that I pass along (https://mikedeboer.github.io/node-github/#api-repos-updateBranchProtection).  This used to work if it wasn't passed in, but I think GitHub has fixed the issue of it being required now, so your codebase will now have to require it.

Closes #536

### PR DESCRIPTION
**Pull request by ryandoll**
for update-branch-protection.

Closes #536

### CODE REVIEW

**Comment by inquilinocdp** [comment]
Please, merge this, it's needed!

**Comment by ryandoll** [comment]
@mikedeboer any chance you could review this one?

**Comment by ryandoll** [comment]
@mikedeboer Your latest code still does not address this.  Can you please merge?

**Comment by mishuagopian** [comment]
Please @mikedeboer !

**Pull request merged**
