### PR TITLE
Update createFromIssue

### PR DESCRIPTION
**Pull request by thom4parisot**
It seems more logical to run `pullRequests.createFromIssue()` with an issue number and because `title` was a mandatory field, it could never work without throwing an error like this

> ERROR event: {"message":"You may only provide an issue number or a title string, but not both.","documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}

### CODE REVIEW

**Comment by BPScott** [comment]
Heeeeey it's Tom!

The code in `lib/routes.json` is generated from content in the [`@octokit/routes`](https://github.com/octokit/routes) repository, which in turn is generated from the Github API docs. In this case, the content at https://developer.github.com/v3/pulls/#create-a-pull-request

This PR would get overwritten the next time update from `@octokit/routes` are pulled in to this repo. The better fix for this issue would be to do something in `@octokit/routes` that handles the "alternative input" headings in the API docs.

**Comment by thom4parisot** [comment]
Ah @BPScott, you here! So funny 🙂 

Thanks for the pointer, super helpful. From what I understand, octokit/routes#200 might be related.

In the meantime, I'll use the experimental `request` API.

Thank you for your help. I hope Vancouver treats you well 🙂

**Comment by BPScott** [comment]
> @BPScott thank you for jumping in and helping out, very much appreciated!

Would have been better if I answered correctly though ;)

**Review by gr2m — APPROVED** [review]
thank you all 💝

**Pull request merged**
