### PR TITLE
chore(package): update @octokit/routes to version 12.0.0

### PR DESCRIPTION
**Pull request by gr2m**
Closes #979. Discussion at #983

### CODE REVIEW

**Comment by gr2m** [comment]
changing the "Installation Access Token" route (https://github.com/octokit/rest.js/pull/982/commits/317eb76f33f1414661f19427fe47616035e9b8db) will break GHE versions 2.13 and older. So I’ll merge this together with the other changes for v16

**Review by bkeepers — APPROVED** [review]
As I mentioned on https://github.com/octokit/rest.js/issues/983#issuecomment-416639571, it looks like the route for installations has been around for well over a year, but the documentation was still pointing to the deprecated route. This should be fine to merge and release as a non-breaking change.

**Comment by BPScott** [comment]
Routes 12.x also includes breaking changes to the checks API (https://github.com/octokit/routes/pull/236 & https://developer.github.com/changes/2018-08-16-changes-to-the-checks-rest-api/). The HTTP API side of this breaking change went live yesterday.

Until this PR is merged I'm unable to update my probot-based app that uses a removed route to use its replacement. (I can't tell my package.json to use this branch as I'm using Typescript and the typescript definitions don't get generated when I do that - thus resulting in lots of "type errors because the typedefs are absent").

Getting this merged and released ASAP if it is not a breaking change would be fantastic.

**Comment by evqna** [comment]
I am in the same boat as @BPScott but managed to work around it by leaving the old parameter keys in the request object:
```javascript
const annotations = {path, start_line, end_line, annotation_level, title, message, blob_href: '', filename: '', warning_level: 'warning'};
``` 

This is JS though, not sure how applicable it is to typescript.

I would be happy to help if needed.

**Comment by eknowles** [comment]
@evqna @gr2m I can't get this working with typescript, 

```
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "CheckRun",
      "code": "invalid",
      "field": "annotations"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/checks/runs/#update-a-check-run"
}
```
if I include...
```
return {
                path: filePath,
                start_line: issue.line,
                end_line: issue.line,
                start_column: issue.column,
                // @ts-ignore
                annotation_level: ANNONTATION_LEVELS[issue.issueType] as string,
                // @ts-ignore
                message: ISSUE_HELP[issue.issueType] as string,
                // @ts-ignore
                title: `Warning with ${issue.issueType} of ${issue[issue.issueType]}`,

                // required
                // @ts-ignore
                warning_level: ANNONTATION_LEVELS[issue.issueType] as any,
                blob_href: '',
                filename: '',
              };
```

otherwise without the blob_href, filename I get 
```
Empty value for parameter 'output.annotations[0].blob_href': undefined
```
😢

**Comment by eknowles** [comment]
@gr2m @bkeepers any way to get this merged?

**Pull request merged**
