### PR TITLE
Add Code of Conduct preview endpoint support ✨

### PR DESCRIPTION
**Pull request by hiimbex**
This PR adds support for the Code of Conduct GitHub API (in preview period) documented here: https://developer.github.com/v3/codes_of_conduct/

Tests and api docs generated. README updated for preview headers. npm requests that I commit the `package-lock.json` file, but please let me know if that is not the case.

cc/ @bkeepers @jbjonesjr

### CODE REVIEW

**Review by bkeepers — APPROVED** [review]
LGTM!

**Comment by zeke** [comment]
Awesome. Didn't know these new endpoints were a thing. 👍 

The test suite is still not working. How can we ship these changes with confidence? Are you folks smoke-testing this stuff?

**Comment by hiimbex** [comment]
> The test suite is still not working. How can we ship these changes with confidence? Are you folks smoke-testing this stuff?

I verified all the end points work by replacing the values in the testing suite with real ones and verifying those work. Since then I've been replacing the package in my `node_modules` with the code from my branch and had success hitting these endpoints.

I agree that this kind of testing doesn't give me great confidence in my changes. I'd be happy to update once we get some new testing infrastructure set up! :)

**Comment by kaizensoze** [comment]
Thanks!

**Comment by zeke** [comment]
Hey @hiimbex!

@gr2m and I have started working on a fork in the octokit org. I tried to pull in the changes from this PR but things have already diverged enough to generate some conflicts.

Can you tell me which files you modified manually to make this change?

**Comment by hiimbex** [comment]
Yes! would it be easier for me to just open a PR there?

If not I edited the README to reflect the preview header and `routes.json`. Everything else was generated, but I think the index files are necessary while the test is ❓

**Comment by zeke** [comment]
> would it be easier for me to just open a PR there?

Yes please 🙏

**Pull request merged**
