### PR TITLE
Update how members are added to teams

### PR DESCRIPTION
**Pull request by masonforest**
https://developer.github.com/changes/2014-08-05-team-memberships-api/

### CODE REVIEW

**Comment by devinsba** [comment]
I hope this can get pulled in. I am working on something that requires this capability. Not time sensitive but certainly would love to see this sooner than later

**Comment by devinsba** [comment]
Now that I have gotten a chance to test this out. These modifications are not working for me.

```
 Error: Unsupported route, not implemented in version 3.0.0 for route 'orgs/add-team-member' and block: {"url":"/teams/:id/memberships/:user","method":"PUT","params":{"$id":null,"$user":null}}
  at /Users/user/src/me/bot/node_modules/github/index.js:338:31
  at Array.forEach (native)
  at prepareApi (/Users/user/src/me/bot/node_modules/github/index.js:316:33)
  at /Users/user/src/me/bot/node_modules/github/index.js:371:21
  at Array.forEach (native)
  at prepareApi (/Users/user/src/me/bot/node_modules/github/index.js:316:33)
  at [object Object].setupRoutes (/Users/user/src/me/bot/node_modules/github/index.js:376:9)
  at new module.exports (/Users/user/src/me/bot/node_modules/github/index.js:193:10)
  at Object.<anonymous> (/Users/user/src/me/bot/scripts/github.js:28:14)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/user/src/me/bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Robot.loadFile (/Users/user/src/me/bot/node_modules/hubot/src/robot.coffee:217:9, <js>:163:20)
  at Robot.load (/Users/user/src/me/bot/node_modules/hubot/src/robot.coffee:239:9, <js>:186:30)
  at HipChat.loadScripts (/Users/user/src/me/bot/node_modules/hubot/bin/hubot:93:5, <js>:94:13)
  at HipChat.emit (events.js:92:17)
  at Connector.<anonymous> (/Users/user/src/me/bot/node_modules/hubot-hipchat/src/hipchat.js:135:13)
  at Connector.emit (events.js:117:20)
  at /Users/user/src/me/bot/node_modules/hubot-hipchat/src/connector.coffee:407:7, <js>:349:22
  at Connector.<anonymous> (/Users/user/src/me/bot/node_modules/hubot-hipchat/src/connector.coffee:125:7, <js>:107:16)
  at Connector.g (events.js:180:16)
  at Connector.emit (events.js:98:17)
  at Connector.onStanza (/Users/user/src/me/bot/node_modules/hubot-hipchat/src/connector.coffee:453:7, <js>:397:21)
  at Client.emit (events.js:95:17)
  at Client.onStanza (/Users/user/src/me/bot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-client/index.js:158:14)
  at Connection.emit (events.js:95:17)
  at Connection.onStanza (/Users/user/src/me/bot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/connection.js:269:14)
  at StreamParser.<anonymous> (/Users/user/src/me/bot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/connection.js:156:14)
  at StreamParser.emit (events.js:95:17)
  at SaxExpat.<anonymous> (/Users/user/src/me/bot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/stream_parser.js:58:22)
  at SaxExpat.emit (events.js:95:17)
  at [object Object].<anonymous> (/Users/user/src/me/bot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/ltx/lib/sax_expat.js:14:14)
  at [object Object].emit (events.js:95:17)
  at [object Object].Parser.parse (/Users/user/src/me/bot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/lib/node-expat.js:18:22)
  at SaxExpat.write (/Users/user/src/me/bot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/ltx/lib/sax_expat.js:24:22)
  at StreamParser.write (/Users/user/src/me/bot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/stream_parser.js:102:21)
  at Connection.onData (/Users/user/src/me/bot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/connection.js:208:21)
  at CleartextStream.<anonymous> (/Users/user/src/me/bot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/connection.js:64:14)
  at CleartextStream.emit (events.js:117:20)
  at CleartextStream.<anonymous> (_stream_readable.js:764:14)
  at CleartextStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at _stream_readable.js:419:7
  at process._tickCallback (node.js:419:13)
```

**Comment by masonforest** [comment]
hey @devinsba. I just made some updates.

Could you try running [this gist](https://gist.github.com/masonforest/59cdf9dd79ee28c64e3b) and see if it works for you?

Thanks for helping test this out.

**Comment by devinsba** [comment]
It worked against the public Github (You might get an email with an invite to the team I have been testing with) but did not against github enterprise

Here is what I got:

```
{ [Error: {"message":"If you would like to help us test the GitHub Team Memberships API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.","documentation_url":"https://developer.github.com/enterprise/2.0/v3/orgs/teams/#add-team-membership"}]
  message: '{"message":"If you would like to help us test the GitHub Team Memberships API during its preview period, you must specify a custom media type in the \'Accept\' header. Please see the docs for full details.","documentation_url":"https://developer.github.com/enterprise/2.0/v3/orgs/teams/#add-team-membership"}',
  code: 415 }
```

**Comment by devinsba** [comment]
Actually, It looks like there is an undocumented config value I can fill in to get that working on Enterprise so that works

```
var github = new GitHubApi({
  version: "3.0.0",
  requestMedia: "application/vnd.github.the-wasp-preview+json",
  host: host,
  pathPrefix: apiPath
});
```

**Comment by mikedeboer** [comment]
@masonforest I'm afraid simply renaming the methods is no good, since GH is providing a transition period for the memberships API update. During this period, this library needs to support both APIs, so the new methods will need to be _added_, not updating the old ones.

Thanks for working on this!

**Comment by kaizensoze** [comment]
New methods added: https://mikedeboer.github.io/node-github/

**Pull request closed without merging**
