### PR TITLE
add X-GitHub-SSO to response-headers

### PR DESCRIPTION
**Pull request by armw4**

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
cheers :)

**Comment by armw4** [comment]
Awesome! Thanks you kindly, good sir (@gr2m). 👍

**Comment by armw4** [comment]
https://developer.github.com/v3/auth/#authenticating-for-saml-sso

**Comment by jameslfc** [comment]
@armw4  I was reading the article you attached above.. What does the statement below actually means?
"Visit the URL specified in X-GitHub-SSO to whitelist the token for the organization."

I was trying to connect to my organization repository with sourcetree.. but I couldn't get it work.. Guess I might not whitelisting my repository correctly..

**Comment by armw4** [comment]
Hmm...it’s been a while since I dealt with this. I recall needling to interrogate the aforementioned response header inside my express.js app to determine if SSO was enabled for an organization. I believe I tenderer an error message of sorts to warn the user they needed to use a token which encapsulates the SSO authorization as opposed to Basic Auth. The token takes SSO into account and is more restrictive as opposed to all encompassing and permissive like Basic Auth (you have to explicitly grant org access, repository access, etc.).

**Comment by armw4** [comment]
Yes! I found it. You need to use a [Personal Access Token](https://help.github.com/en/github/authenticating-to-github/about-authentication-with-saml-single-sign-on) to access web resources when SSO is enabled. It allows the admin to track your access and tokens (great for Enterprise-Grade organizations). I encountered this while building an Atlassian Connect Express Jira Cloud add-on.

**Comment by jameslfc** [comment]
@armw4  Thank you so much for responding so quick, and spending time on researching this
Unfortunately I wan't get Sourcetree work even with the Personal Access Token.. I changed to use GitKraken, and it seems much easier to setup ... 
But thanks again ((I hope I can offer you a beer)...

**Comment by armw4** [comment]
Haha..no problem sir have a great 21st of October, 2019 ⭐️ 🌍 ☮️

**Pull request merged**
