### PR TITLE
Fix link to promise example

### PR DESCRIPTION
**Pull request by vkentta**
* Remove outdated links
* Add new link to current example

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
Kiitos, Ville! 👍

**Comment by zeke** [comment]
TIL

image

I wonder if that's where "kudos" came from?

**Comment by vkentta** [comment]
Kudos is actually also a Finnish word. Little bit different meaning though :smile:

**Comment by zeke** [comment]
What's the difference?

**Comment by vkentta** [comment]
https://fi.wikipedia.org/wiki/Kudos

**Pull request merged**
